name: Build Js Port

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install peg
      run: go get -u github.com/pointlander/peg

    - name: Install peg
      run: go install github.com/pointlander/peg

    - name: Install gopherjs
      run: go get -u github.com/gopherjs/gopherjs@v1.18.0-beta1+go1.18.5

    - name: Install gopherjs
      run: go install github.com/gopherjs/gopherjs@v1.18.0-beta1+go1.18.5

    - name: Code gen
      run: peg -switch -inline roll.peg

    - name: Build
      run: gopherjs build github.com/sealdice/dicescript/jsport -o jsport/dicescript.js
